name: flutter_projem
description: "Kombin uygulamasÄ± (offline)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  uuid: ^4.5.1
  crypto: ^3.0.3
  json_annotation: ^4.9.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true